Reservation/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'', include('authentication.urls', namespace='authentication')),
    url(r'^visage/', include('visage.urls', namespace='visage')),
]

authentication/urls.py
from authentication import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^singup/$', views.singup, name='singup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

visage/urls.py
from visage import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^selfs_list/$', views.selfs_list, name='selfs_list'),
    url(r'^charge_credit/$', views.charge_credit, name='charge_credit'),
    url(r'^add_food/$', views.add_food, name='add_food'),
    url(r'^add_self/$', views.add_self, name='add_self'),
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^reservation_list/(?P<sname>[A-Za-z0-9._\-آ-ی ]+)/$', views.reservation_list, name='reservation_list'),
]

templates/add_food.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>افزودن غذا • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>

<div class="topbar row">
    <div class="columns topbar__title">
        <a href="{% url "visage:home" %}">
            <strong>سرویس رزرواسیون</strong>
        </a>
    </div>

    <div class="columns shrink">
        {% if is_admin %}
        <a class="topbar-link" href="{% url "visage:add_self" %}" title="افزودن سلف">
            <i class="fa fa-plus fa-middle"></i> افزودن سلف
        </a>

        <a class="topbar-link active" href="{% url "visage:add_food" %}" title="افزودن غذا">
            <i class="fa fa-plus fa-middle"></i> افزودن غذا
        </a>

        <a class="topbar-link" href="{% url "visage:schedule" %}" title="تقویم غذایی">
            <i class="fa fa-calendar fa-middle"></i> تقویم غذایی
        </a>
        {% else %}
        <a class="topbar-link" href="{% url "visage:charge_credit" %}" title="برای افزایش اعتبار کلیک کنید">
            اعتبار: <span class="topbar-credit">{{ credit }}</span> تومان
        </a>
        {% endif %}
        <a class="topbar-link topbar-logout" href="{% url "authentication:logout" %}" title="خروج از سیستم">
            <i class="fa fa-sign-out"></i>
            <span>خروج از سیستم</span>
        </a>
    </div>
</div>

<div class="row content">
    <div class="small-12 columns">
        <nav aria-label="You are here:" role="navigation">
            <ul class="breadcrumbs">
                <li><a href="{% url "visage:home" %}">صفحه اصلی</a></li>
                <li>
                    افزودن غذا
                </li>
            </ul>
        </nav>

        <h1>
            افزودن غذا
        </h1>

        <form method="post" action="{% url "visage:add_food" %}">
            {% csrf_token %}
            <div class="row">
                <div class="small-12 medium-6 columns">
                    <label>
                        نام غذا
                        <input type="text" name="name">
                    </label>
                </div>
                <div class="small-12 medium-6 columns">
                    <label for="price">
                        قیمت
                    </label>
                    <div class="input-group">
                        <input class="input-group-field" id="price" type="number" min="0" name="price">
                        <span class="input-group-label">تومان</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="small-12 columns">
                    <label>
                        توضیحات
                        <textarea rows="4" id="description" name="description"></textarea>
                    </label>
                </div>
            </div>

            <div class="row align-right">
                <div class="columns small-12 medium-3 large-2">
                    <button class="button expanded" type="submit">افزودن</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/foundation-datepicker.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>

templates/add_self.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>افزودن سلف • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>

<div class="topbar row">
    <div class="columns topbar__title">
        <a href="{% url "visage:home" %}">
            <strong>سرویس رزرواسیون</strong>
        </a>
    </div>

    <div class="columns shrink">
        {% if is_admin %}
        <a class="topbar-link active" href="{% url "visage:add_self" %}" title="افزودن سلف">
            <i class="fa fa-plus fa-middle"></i> افزودن سلف
        </a>

        <a class="topbar-link" href="{% url "visage:add_food" %}" title="افزودن غذا">
            <i class="fa fa-plus fa-middle"></i> افزودن غذا
        </a>

        <a class="topbar-link" href="{% url "visage:schedule" %}" title="تقویم غذایی">
            <i class="fa fa-calendar fa-middle"></i> تقویم غذایی
        </a>
        {% else %}
        <a class="topbar-link" href="{% url "visage:charge_credit" %}" title="برای افزایش اعتبار کلیک کنید">
            اعتبار: <span class="topbar-credit">{{ credit }}</span> تومان
        </a>
        {% endif %}
        <a class="topbar-link topbar-logout" href="{% url "authentication:logout" %}" title="خروج از سیستم">
            <i class="fa fa-sign-out"></i>
            <span>خروج از سیستم</span>
        </a>
    </div>
</div>

<div class="row content">
    <div class="small-12 columns">
        <nav aria-label="You are here:" role="navigation">
            <ul class="breadcrumbs">
                <li><a href="{% url "visage:home" %}">صفحه اصلی</a></li>
                <li>
                    افزودن سلف
                </li>
            </ul>
        </nav>

        <h1>
            افزودن سلف
        </h1>

        <form method="post" action="{% url "visage:add_self" %}">
            {% csrf_token %}
            <div class="row">
                <div class="small-12 medium-3 large-2 columns">
                    <label for="name" class="text-left middle">نام سلف</label>
                </div>
                <div class="small-12 medium-9 large-10 columns">
                    <input type="text" id="name" name="name">
                </div>
            </div>
            <div class="row">
                <div class="small-12 medium-3 large-2 columns">
                    <label for="address" class="text-left middle">آدرس سلف</label>
                </div>
                <div class="small-12 medium-9 large-10 columns">
                    <input type="text" id="address" name="address">
                </div>
            </div>
            <div class="row">
                <div class="small-12 medium-3 large-2 columns">
                    <label for="description" class="text-left middle">توضیحات</label>
                </div>
                <div class="small-12 medium-9 large-10 columns">
                    <textarea rows="4" id="description" name="description"></textarea>
                </div>
            </div>

            <div class="row align-right">
                <div class="columns small-12 medium-3 large-2">
                    <button class="button expanded" type="submit">افزودن</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/foundation-datepicker.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>

templates/charge_credit.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>افزایش اعتبار • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>

<div class="topbar row">
    <div class="columns topbar__title">
        <a href="{% url "visage:home" %}">
            <strong>سرویس رزرواسیون</strong>
        </a>
    </div>

    <div class="columns shrink">
        {% if is_admin %}
        <a class="topbar-link" href="{% url "visage:add_self" %}" title="افزودن سلف">
            <i class="fa fa-plus fa-middle"></i> افزودن سلف
        </a>

        <a class="topbar-link" href="{% url "visage:add_food" %}" title="افزودن غذا">
            <i class="fa fa-plus fa-middle"></i> افزودن غذا
        </a>

        <a class="topbar-link" href="{% url "visage:schedule" %}" title="تقویم غذایی">
            <i class="fa fa-calendar fa-middle"></i> تقویم غذایی
        </a>
        {% else %}
        <a class="topbar-link active" href="{% url "visage:charge_credit" %}" title="برای افزایش اعتبار کلیک کنید">
            اعتبار: <span class="topbar-credit">{{ credit }}</span> تومان
        </a>
        {% endif %}
        <a class="topbar-link topbar-logout" href="{% url "authentication:logout" %}" title="خروج از سیستم">
            <i class="fa fa-sign-out"></i>
            <span>خروج از سیستم</span>
        </a>
    </div>
</div>

<div class="row content">
    <div class="small-12 columns">
        <nav aria-label="You are here:" role="navigation">
            <ul class="breadcrumbs">
                <li><a href="{% url "visage:home" %}">صفحه اصلی</a></li>
                <li>
                    اعتبار حساب
                </li>
            </ul>
        </nav>
        <h1>اعتبار حساب</h1>
        <p>اعتبار حساب شما <strong>{{ credit }}</strong> تومان است. مبلغ مورد نظر برای افزایش اعتبار حساب را وارد کنید.</p>

        <form class="row align-left" method="post" action="{% url "visage:charge_credit" %}">
            <div class="columns small-12 medium-6 large-4">
                {% csrf_token %}
                {% if error %}
                    <div class="alert callout">
                        <p><i class="fi-alert"></i>{{ error }}</p>
                    </div>
                {% endif %}
                <div class="input-group">
                    <input class="input-group-field" type="number" name="credit">
                    <span class="input-group-label">تومان</span>
                </div>
            </div>
            <div class="columns small-12">
                <button class="button small" type="submit">افزایش اعتبار</button>
            </div>
        </form>
    </div>
</div>

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ورود • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>
<div class="row column align-center medium-6 large-4 container-padded">
    <form class="log-in-form" method="post" action="{% url "authentication:login" %}">
        {% csrf_token %}
        <h4 class="text-center">ورود به پنل کاربری</h4>

        {% if error %}
            <div class="alert callout">
                <p><i class="fi-alert"></i>{{ error }}</p>
            </div>
        {% endif %}

        <label>ایمیل
            <div class="input-group">
                <span class="input-group-label" dir="ltr">@ut.ac.ir</span>
                <input class="input-group-field" type="text" name="email" dir="ltr" required>
            </div>
        </label>
        <label>رمز عبور
            <input type="password" name="password" dir="ltr" required>
        </label>
        <p><input type="submit" class="button expanded" value="ورود"></p>
        <p class="text-center">
            اکانت کاربری ندارید؟ <a href="{% url "authentication:singup" %}">ثبت‌نام</a>
        </p>
    </form>
</div>





<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>

templates/reservation_list.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>لیست غذاهای ۷ روز آینده • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>

<div class="topbar row">
    <div class="columns topbar__title">
        <a href="{% url "visage:home" %}">
            <strong>سرویس رزرواسیون</strong>
        </a>
    </div>

    <div class="columns shrink">
        {% if is_admin %}
        <a class="topbar-link" href="{% url "visage:add_self" %}" title="افزودن سلف">
            <i class="fa fa-plus fa-middle"></i> افزودن سلف
        </a>

        <a class="topbar-link" href="{% url "visage:add_food" %}" title="افزودن غذا">
            <i class="fa fa-plus fa-middle"></i> افزودن غذا
        </a>

        <a class="topbar-link" href="{% url "visage:schedule" %}" title="تقویم غذایی">
            <i class="fa fa-calendar fa-middle"></i> تقویم غذایی
        </a>
        {% else %}
        <a class="topbar-link" href="{% url "visage:charge_credit" %}" title="برای افزایش اعتبار کلیک کنید">
            اعتبار: <span class="topbar-credit">{{ credit }}</span> تومان
        </a>
        {% endif %}
        <a class="topbar-link topbar-logout" href="{% url "authentication:logout" %}" title="خروج از سیستم">
            <i class="fa fa-sign-out"></i>
            <span>خروج از سیستم</span>
        </a>
    </div>
</div>

<div class="row content">
    <div class="small-12 columns">
        <nav aria-label="You are here:" role="navigation">
            <ul class="breadcrumbs">
                <li><a href="{% url "visage:home" %}">صفحه اصلی</a></li>
                <li>
                    {{ sname }}
                </li>
            </ul>
        </nav>

        <h1>
            {{ sname }} <small><span class="fa fa-info-circle fa--middle has-tip" data-tooltip aria-haspopup="true" data-disable-hover="false" tabindex="1" title="{{ description }}"></span></small>
        </h1>
        <p><strong>آدرس: </strong>{{ address }}</p>

        {% if warn %}
            <div class="warning callout">
                <p><i class="fi-alert"></i>{{ warn }}</p>
            </div>
        {% endif %}
        <form method="post" action="{% url "visage:reservation_list" sname %}">
            {% csrf_token %}
            <table class="hover reserve-list">
                <thead>
                <tr>
                    <th width="200">تاریخ</th>
                    <th>غذا</th>
                    <th width="150">توضیحات</th>
                    <th width="150">قیمت</th>
                    <th width="150">سفارش داده شده</th>
                    <th width="150">تعداد سفارش</th>
                </tr>
                </thead>
                <tbody>
                {% for choice in choices %}
                    <tr>
                        <td>{{ choice.0 }}</td>
                        <td>{{ choice.1 }}</td>
                        <td>{{ choice.2 }}</td>
                        <td>{{ choice.3 }}</td>
                        <td>{{ choice.4 }}</td>
                        <td>
                            <input type="number" name="{{ sname }}#{{ choice.1 }}#{{ choice.0 }}" min="0" value="0">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="row align-right">
                <div class="columns small-12 medium-3 large-2">
                    <button class="button expanded" type="submit">سفارش</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>

templates/schedule.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>تقویم غذایی • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>

<div class="topbar row">
    <div class="columns topbar__title">
        <a href="{% url "visage:home" %}">
            <strong>سرویس رزرواسیون</strong>
        </a>
    </div>

    <div class="columns shrink">
        {% if is_admin %}
            <a class="topbar-link" href="{% url "visage:add_self" %}" title="افزودن سلف">
                <i class="fa fa-plus fa-middle"></i> افزودن سلف
            </a>

            <a class="topbar-link" href="{% url "visage:add_food" %}" title="افزودن غذا">
                <i class="fa fa-plus fa-middle"></i> افزودن غذا
            </a>

            <a class="topbar-link active" href="{% url "visage:schedule" %}" title="تقویم غذایی">
                <i class="fa fa-calendar fa-middle"></i> تقویم غذایی
            </a>
        {% else %}
            <a class="topbar-link" href="{% url "visage:charge_credit" %}" title="برای افزایش اعتبار کلیک کنید">
                اعتبار: <span class="topbar-credit">{{ credit }}</span> تومان
            </a>
        {% endif %}
        <a class="topbar-link topbar-logout" href="{% url "authentication:logout" %}" title="خروج از سیستم">
            <i class="fa fa-sign-out"></i>
            <span>خروج از سیستم</span>
        </a>
    </div>
</div>

<div class="row content">
    <div class="small-12 columns">
        <nav aria-label="You are here:" role="navigation">
            <ul class="breadcrumbs">
                <li><a href="{% url "visage:home" %}">صفحه اصلی</a></li>
                <li>
                    تقویم غذایی
                </li>
            </ul>
        </nav>

        <h1>
            تقویم غذایی
        </h1>

        <form method="post" action="{% url "visage:schedule" %}">
            {% csrf_token %}
            <div class="row">
                <div class="small-12 medium-3 columns">
                    <label>
                        غذاها
                        <select name="food">
                            {% for food in foods %}
                                <option value="{{ food.0 }}">{{ food.0 }}</option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
                <div class="small-12 medium-3 columns">
                    <label>
                        سلف‌ها
                        <select name="self">
                            {% for self in selfs %}
                                <option value="{{ self.0 }}">{{ self.0 }}</option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
                <div class="small-12 medium-3 columns">
                    <label>
                        تعداد
                        <input type="number" name="count" min="1" value="1">
                    </label>
                </div>
                <div class="small-12 medium-3 columns">
                    <label>
                        تاریخ
                        <input type="text" name="due_date" id="due_date" data-date-format="yyyy-mm-dd">
                    </label>
                </div>
            </div>

            <div class="row align-right">
                <div class="columns small-12 medium-3 large-2">
                    <button class="button expanded" type="submit">افزودن</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/foundation-datepicker.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>

templates/selfs_list.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>صفحه اصلی • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>
<div class="topbar row">
    <div class="columns topbar__title">
        <a href="{% url "visage:home" %}">
            <strong>سرویس رزرواسیون</strong>
        </a>
    </div>

    <div class="columns shrink">
        {% if is_admin %}
        <a class="topbar-link active" href="{% url "visage:add_self" %}" title="افزودن سلف">
            <i class="fa fa-plus fa-middle"></i> افزودن سلف
        </a>

        <a class="topbar-link" href="{% url "visage:add_food" %}" title="افزودن غذا">
            <i class="fa fa-plus fa-middle"></i> افزودن غذا
        </a>

        <a class="topbar-link" href="{% url "visage:schedule" %}" title="تقویم غذایی">
            <i class="fa fa-calendar fa-middle"></i> تقویم غذایی
        </a>
        {% else %}
        <a class="topbar-link" href="{% url "visage:charge_credit" %}" title="برای افزایش اعتبار کلیک کنید">
            اعتبار: <span class="topbar-credit">{{ credit }}</span> تومان
        </a>
        {% endif %}
        <a class="topbar-link topbar-logout" href="{% url "authentication:logout" %}" title="خروج از سیستم">
            <i class="fa fa-sign-out"></i>
            <span>خروج از سیستم</span>
        </a>
    </div>
</div>

<div class="row content">
    <div class="small-12 columns">
        <h1>انتخاب سلف</h1>
        <ul>
            {% for self in selfs %}
                <li><a href="{% url "visage:reservation_list" self.0 %}">{{ self.0 }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ثبت‌نام • سیستم رزرواسون</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/reservation-v1.0.0.css" %}">

    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>

</head>
<body>
<div class="row column align-center medium-6 large-4 container-padded">
    <form class="log-in-form" method="post" action="{% url "authentication:singup" %}">
        {% csrf_token %}
        <h4 class="text-center">ثبت‌نام</h4>

        {% if error %}
            <div class="alert callout">
                <p><i class="fi-alert"></i>{{ error }}</p>
            </div>
        {% endif %}

        <label>ایمیل
            <div class="input-group">
                <span class="input-group-label" dir="ltr">@ut.ac.ir</span>
                <input class="input-group-field" type="text" name="email" dir="ltr" required>
            </div>
        </label>
        <label>رمز عبور
            <input type="password" name="password" dir="ltr" required>
        </label>
        <label>نام
            <input type="text" name="fname" required>
        </label>
        <label>نام خانوادگی
            <input type="text" name="lname" required>
        </label>
        <p><input type="submit" class="button expanded" value="ثبت‌نام"></p>
        <p class="text-center">
            اکانت کاربری دارید؟ <a href="{% url "authentication:login" %}">ورود</a>
        </p>
    </form>
</div>





<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/reservation-v1.0.0.js" %}"></script>
</body>
</html>